name: run-tests

on:
  pull_request:
  push:

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: install dependencies
        run: pip install .
        shell: bash

      - name: install pytest
        run: pip install pytest
        shell: bash

      - name: run test
        run: pytest
        shell: bash
