name: run-tests

on:
  pull_request:
  push:

jobs:
  run-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }} 

      - name: install dependencies
        run: pip install .[dev]
        shell: bash

      - name: run Ruff linter
        run: ruff check .
        shell: bash

      - name: run test
        run: pytest -rs
        shell: bash
